name: "fr_model"
platform: "onnxruntime_onnx"
max_batch_size: 8

input {
  name: "input"
  data_type: TYPE_FP32
  dims: [3, 112, 112]
}

output {
  name: "embedding"
  data_type: TYPE_FP32
  dims: [512]
}

dynamic_batching {
  max_queue_delay_microseconds: 100
}

instance_group {
  kind: KIND_CPU
}

